#!/bin/bash

show_help () {
  echo "Usage: docker-tags [OPTIONS] <REPOSITORY>
Retrieve tag list of a Docker repository.

REPOSITORY: Name of repository.

OPTIONS:
  -h, --hide-pagination
         Don't show pagination.
  -p, --page-size
         Number of tag per page. Due to Docker registry API limitation, maximum value is 100.
         Default is 100.
  -s, --sort=WORD
         Sort tags by WORD. Possible values for WORD are 'last_updated' or 'name'.
         When sort by name, order is alphabetically inversed to show highest version numbers first.
         Default is 'last_updated'.
  --help
         Show help.

Examples: docker-tags ubuntu/bind9
          docker-tags -hs name php"
}

# Don't understand why but whether the repository name contain "/" in its name, registry address must be diffrent !
# If someone has an idea...

REGISTRY_FOR_REPO_WITHOUT_SLASH="https://registry.hub.docker.com"
REGISTRY_FOR_REPO_WITH_SLASH="https://hub.docker.com"
SORT=last_updated
PAGE_SIZE=100
HIDE_PAGES=0

options=$(getopt -o hp:s: -l hide-pagination,page-size:sort:,help -- "$@")
eval set -- "$options"
while true; do
  case "$1" in
    -h|--hide-pagination)
      HIDE_PAGES=1
      shift
      ;;
    -p|--page-size)
      PAGE_SIZE=$2
      shift 2
      ;;
    -s|--sort)
      SORT="$2"
      shift 2
      ;;
    --help)
      show_help
      exit
      ;;
    --)
      shift
      break
      ;;
  esac
done

REPO="$1"
shift

throw_error () {
  MSG=$1
  STD_MSG="Command stopped"
  printf "\033[0;31mError: $MSG\033[0m\n"
  echo "$STD_MSG"
  exit 1
}

# Requirements
command -v curl >/dev/null 2>&1 || throw_error "curl is not installed. Aborting."
command -v jq >/dev/null 2>&1 || throw_error "jq is not installed. Aborting."

# Command arguments checks
[ -z $REPO ] && show_help && throw_error "Please specify a repository name (ie. docker-tags php)"
[ $PAGE_SIZE -lt 0 ] && show_help && throw_error "Page size must be greater than 0"
[ $PAGE_SIZE -gt 100 ] && show_help && throw_error "Page size must be lower than 100"
[ $SORT != "last_updated" ] && [ $SORT != "name" ] && show_help && throw_error "Bad sort value"

# Select registry depending of repository name
if [[ ! "$REPO" =~ "/" ]]; then
  url="$REGISTRY_FOR_REPO_WITHOUT_SLASH/v2/repositories/library/$REPO/tags"
else
  url="$REGISTRY_FOR_REPO_WITH_SLASH/v2/repositories/$REPO/tags"
fi

# Get tags count
count=$(curl "$url/?page=1&page_size=1" 2>/dev/null | jq '."count"')

# Calculate page count
page_count=$(((count / PAGE_SIZE) + (count % PAGE_SIZE > 0)))

# Loop through pages
for (( i=1; i<=$page_count; i++ )); do
   [[ $HIDE_PAGES = 0 ]] && echo "- Page $i/$page_count -"
   curl "$url/?page=$i&page_size=$PAGE_SIZE&ordering=$SORT" 2>/dev/null | jq -r '."results"[]["name"]'
done
