name: Tests with Bats

on:
  push:
    branches:
      - main
    paths:
      - docker-tags
  pull_request:
    branches:
      - main
      - dev
    paths:
      - docker-tags

jobs:
  bats:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup Bats
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.10.0
      -
        name: Test
        run: bats -r .
