name: Tests with Bats

on:
  - push
  - pull_request

jobs:
  bats:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup Bats
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.10.0
      -
        name: Test
        run: bats -r .
