name: Docker hub description

on:
  push:
    branches:
      - main
    paths:
      - README.dockerhub.md
      - .github/workflows/dockerhub-description.yml

jobs:
  dockerhub-description:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: benjaminferon/docker-tags
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.dockerhub.md